### PR TITLE
Added try_gethostname function.

### PR DESCRIPTION
**Pull request by rustonaut**
While normally failing to get the hostname
can only happen on a fundamentally broken or
misconfigured system it still is nice to use
the same error handling methods as used for
other failable components instead of having
a panic.

### CODE REVIEW

**Comment by rustonaut** [comment]
I did run into a problem with failing `gethostname()` 3 or so year ago (so not with rust). So it's clearly a think which can happen. Through it only happens with some very broken systems.

Sure, for a lot of use cases you don't want to continue if this fails, but depending on your software stack you still might prefer a error based error handling instead of a panic (shutdown of other parts of the system, better CLI output, etc.).

Also there are a view cases where you don't care if it fails, e.g. if you only use it for better debug messages and your program might still run normal even on that broken system (or might help you find out what is broken!).

---

I don't remember the details from back then but they where something on the line of:
- Unusual linux setup.
- and missing or broken `/etc/hostname` and/or `/etc/host`.
- and broken/non standard conform company DNS server.

**Comment by rustonaut** [comment]
I looked a bit more into it:

It seems that glibc returns the uname's nodename instead of using the systemcall and is close to impossible to fail. I will see if I can find out what it does for other libc's.

Still it's nice if you can just normally integrate it into your software stack and not bother about it anymore, even if that case is never hit (handling the error is less work then just a fractal of the people using the library wondering about if it's needed to be handled and researching it :wink: ).

**Comment by rustonaut** [comment]
So musl does that, too.

I still think it's best to export a way to handle the error as for everyone like me it's way easier to just handle the error then to consider weather or not you really have to handle it. Also `gethostname` just works same as before wrt. to all aspects so it doesn't really cost anything.

**Comment by lunaryorn** [comment]
Thank you for you effort :) but really, what's this for? You've said yourself that `gethostname` failing is "close to impossible".  

I'm sorry but a hazy memory about some failure three years ago won't do for me.  I'd like to see an actual reproducible demo triggering the `panic!` in this library on a reasonable POSIX-compliant system.

For, you know, this _does_ cost something: My time in maintaining, and more importantly, user's time and effort in making an informed decision about which function they should use.

**Comment by rustonaut** [comment]
My standpoint came from how POSIX specified gethostname. I.e. it states that it can fail and that to long names get truncated, it never specifies that truncating means failure :man_facepalming:  nor that there can't be another failure cause. So even through it happens to likely be not failable on (current) glibc/musl we can't say for sure, that it won't do so on other unix like operating system (like Mac) or with the linux system call or newer/older versions of glibc/musl. 

Also anyone being aware that it can theoretically fail (e.g. because they handled it in C) will wonder why it can't in rust and then has to consider if it really can't practically fail and therefore if they can just use that library, which takes way more time then just handling that error.

Lastly I came to the conclusion that panic probably still is fine. I mean even if it could fail, in practice it doesn't. At last on linux(glibc,musl)/windows. Which means that most software probably doesn't handle the error and as such any other platform would likely try to make it, infailable, too. Or risk a lot more software porting problems. (Note that with "it doesn't fail" I mean "it doesn't fail if the name buffer pointer points to a valid buffer and len is equals or grater HOST_NAME_MAX, but not to big either).

**Pull request closed without merging**
